services:
  storage:
    build: ./services/storage/
    container_name: vaito_storage
    restart: unless-stopped
    depends_on: 
      - postgres_db
    networks:
      - vaito_inner_net
    env_file:
      - .env

  gateway:
    build: ./services/gateway/
    container_name: vaito_gateway
    restart: unless-stopped
    networks:
      - vaito_inner_net
      - vaito_outer_net
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    env_file:
      - .env

  postgres_db:
    image: postgres:18
    container_name: vaito_postgres
    restart: unless-stopped
    volumes:
      - vaito_postgres_db:/var/lib/postgresql
    networks:
      - vaito_inner_net
    ports:
      - '127.0.0.1:5432:5432'
    env_file:
      - .env

volumes:
  vaito_postgres_db:

networks:
  vaito_outer_net:
    name: vaito_outer_net
    driver: bridge
  vaito_inner_net:
    name: vaito_inner_net
    driver: bridge

