#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    CREATE USER $USER_DB_USER WITH PASSWORD '$USER_DB_PASS';
    CREATE DATABASE $USER_DB_NAME OWNER $USER_DB_USER;

    CREATE USER $LISTING_DB_USER WITH PASSWORD '$LISTING_DB_PASS';
    CREATE DATABASE $LISTING_DB_NAME OWNER $LISTING_DB_USER;

    GRANT ALL PRIVILEGES ON DATABASE $USER_DB_NAME TO $USER_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $LISTING_DB_NAME TO $LISTING_DB_USER;
EOSQL
