CREATE TABLE IF NOT EXISTS categories (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS listing_statuses (
  id BIGSERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS permissions (
  id BIGSERIAL PRIMARY KEY,
  code TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
  id BIGSERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS roles_permissions (
  role_id BIGSERIAL NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id BIGSERIAL NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash BYTEA NOT NULL,
  role_id BIGSERIAL NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS listings (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category_id BIGSERIAL NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  user_id BIGSERIAL NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  published_at TIMESTAMP(0) WITH TIME ZONE,
  version INTEGER NOT NULL DEFAULT 1,
  status_id BIGSERIAL NOT NULL REFERENCES listing_statuses (id) ON DELETE RESTRICT,
  price BIGINT
);
