CREATE TABLE IF NOT EXISTS categories (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS listing_statuses (
  id BIGSERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS listings (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category_id BIGSERIAL NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  user_id BIGSERIAL NOT NULL,
  created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
  published_at TIMESTAMP(0) WITH TIME ZONE,
  version INTEGER NOT NULL DEFAULT 1,
  status_id BIGSERIAL NOT NULL REFERENCES listing_statuses (id) ON DELETE RESTRICT,
  price BIGINT
);
